data_paths:
  game_feature_derived: "data/game_feature_derived_enc.csv"
  master_game_features: "data/master_game_features.csv"
  user_plays_path: "data/user_plays_enc_small.csv"
coefficients:
  content_based_feature_derived: 0.1
  content_based_master_game: 0.1
  collaborative_filtering: 0.8
test:
  lower_bound: 3
  upper_bound: 200
  test_train_ratio: 0.2
  precision_at_k: 5
  feature_label_ratio: 0.75

